add-booking
mybogdan/java-shareit pull request #2
Opened 2023-12-07 19:10 UTC by mybogdan

2023-12-08 14:23 UTC, Yang-Pi requested changes

2023-12-08 14:23 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +public class BookingService {
Лучше придерживаться модели интерфейс + реализация, те BookingService дб интерфейсом, а текущий функционал вынесен в класс BookingServiceImpl, и то же самое для репозитория. Так появляется некая гибкость в проектировании, когда практически бесшовно можно подменить, например, репозиторий in-memory на бд и обратно.

2023-12-08 14:23 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    public BookingInfoDto updateBookingStatus(Long userId, Long bookingId, Boolean approved) {
Довольно тонкий момент тут: Boolean - это не примитив, а объект, поэтому значение approved может быть и null. Чтобы избежать возможных проблем с этим, используй примитивный тип boolean, чтобы всегда строго либо true, либо false

2023-12-08 14:23 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        User user = userRepository.findById(userId).orElseThrow(()
Рекомендация: переноси .orElseThrow, не только new..., так будет чуть более читаемо

2023-12-08 14:23 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingInfoDto addBooking(@RequestHeader(USERID_HEADER) Long userId, @RequestBody BookingDto booking) {
Все-таки настоятельно рекомендую сделать валидацию на уровне модели dto, чтобы как минимум фильтровать запросы с незаполненными полями. Это повышает эффективность приложения с точки зрения того, что сервис даже не будет вызван для таких запросов.

2023-12-08 14:23 UTC, Yang-Pi commented on src/main/resources/schema.sql
Добавь еще описание для foreign keys, чтобы также показывать связи между таблицами

2023-12-08 14:24 UTC, Yang-Pi commented
+ добавь логирование для успешных операций и ошибок, которые возникают

2023-12-09 12:11 UTC, mybogdan commented on src/main/resources/schema.sql
Не совсем понял. На строках foreign keys после REFERENCES указано отношение к другим таблицам, просто сделал не в отдельной строке. 
Не заметил просто или имеешь ввиду что-то другое?

2023-12-09 13:55 UTC, mybogdan commented
> * добавь логирование для успешных операций и ошибок, которые возникают

Не нашел информации как добавить в конструкцию ".orElseThrow(() -> new ObjectNotFoundException("Пользователь не найден."));" логирование.

2023-12-10 13:45 UTC, Yang-Pi commented
> > * добавь логирование для успешных операций и ошибок, которые возникают
> 
> Не нашел информации как добавить в конструкцию ".orElseThrow(() -> new ObjectNotFoundException("Пользователь не найден."));" логирование.

orElseThrow(() -> {log.error("Info about error"); return new ObjectNotFoundException("Пользователь не найден.");})

2023-12-10 13:45 UTC, Yang-Pi approved these changes

2023-12-17 11:18 UTC, merged